### ISSUE TITLE
 I don't generate the code

### ISSUE THREAD

**Issue by EliuFlorez** [Perfare/Il2CppDumper#222]
Hi guys, you know I don't generate the code just the functions or class in Unity 2017.4.35f1
Il2CppDumper: v5.0.4
Unity: 2017.4.35f1

Note: if you do not provide all of the following information I will directly ignore and close this issue

- Il2CppDumper version

- Target Unity version

- Describe the issue

- Upload executable file and global-metadata.dat

**Comment by EliuFlorez** [comment]
metadata: https://gofile.io/?c=md4nEt

**Comment by EliuFlorez** [comment]
Error block null
```
[Address(RVA = "0x594254", Offset = "0x594254")]
public PlayerController GetDeadPlayer()
{
	/*Error: Unexpected end of block*/;
}
```

**Comment by SilverDash** [comment]
Same issue here. Is this the result of obfuscated code? Could be protected.

**Comment by SilverDash** [comment]
I did read the readme though. States we don't get code. But Is there an explanation why this is the case..?

**Comment by EliuFlorez** [comment]
@SilverDash Well the idea of ​​obtaining the source code of C # its logical conditions etc. it's just to see how it works or to see make a similar game. But I don't know why this is the case. I just know that the functions and logic are not in the DLL

**Comment by EliuFlorez** [comment]
Ok guys I already have the Assets and the Code finally decompiled. but now in what way can I know that Scripts contained the Assets associated with it. ???

**Comment by EliuFlorez** [comment]
For example, guys with this data, how can I know what the scripts are? which has the associated GameObject associated.
```
MonoBehaviour:
  m_GameObject: {fileID: 106}
  m_Enabled: 1
  m_EditorHideFlags: 0
  m_Script: {fileID: 11500000, guid: 17118a165f8ee8749a17df27da28a38e, type: 3}
  m_Name:
  m_EditorClassIdentifier:
--- !u!114 &633
```
